/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import controlador.ClienteControlador;

/**
 *
 * @author Roberto
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form VistaInventario
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgInventario = new javax.swing.JPanel();
        Panel = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        BtnAgregar = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BgOperaciones = new javax.swing.JPanel();
        NombreTxt = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        TelefonoTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        DireccionLabel = new javax.swing.JLabel();
        DireccionTxt = new javax.swing.JTextField();
        TipoLabel = new javax.swing.JLabel();
        TipoSeleccion = new javax.swing.JComboBox<>();
        NotaLabel = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BgInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Panel.setViewportView(TablaDatos);

        BgInventario.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 780, 310));

        BtnAgregar.setText("Agregar");
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        BgInventario.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 110, 35));

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloLabel.setText("INFORMACIÓN DE CLIENTES");
        BgInventario.add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        BtnActualizar.setText("Actualizar");
        BtnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BgInventario.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 110, 35));

        BtnBorrar.setText("Borrar");
        BtnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BgInventario.add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 110, 35));

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BgInventario.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 110, 35));

        BgOperaciones.setBackground(new java.awt.Color(204, 204, 204));
        BgOperaciones.setForeground(new java.awt.Color(204, 204, 204));

        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        NombreLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NombreLabel.setText("Nombre:");

        TelefonoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TelefonoLabel.setText("Telefono:");

        TelefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoTxtActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailLabel.setText("Email:");

        DireccionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DireccionLabel.setText("Dirección:");

        TipoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TipoLabel.setText("Tipo:");

        TipoSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Empresa" }));

        javax.swing.GroupLayout BgOperacionesLayout = new javax.swing.GroupLayout(BgOperaciones);
        BgOperaciones.setLayout(BgOperacionesLayout);
        BgOperacionesLayout.setHorizontalGroup(
            BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgOperacionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BgOperacionesLayout.createSequentialGroup()
                        .addComponent(NombreLabel)
                        .addGap(241, 241, 241)
                        .addComponent(DireccionLabel))
                    .addGroup(BgOperacionesLayout.createSequentialGroup()
                        .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(BgOperacionesLayout.createSequentialGroup()
                                .addComponent(TipoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(TipoSeleccion, 0, 204, Short.MAX_VALUE))
                            .addComponent(NombreTxt)
                            .addComponent(TelefonoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefonoTxt))
                        .addGap(50, 50, 50)
                        .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel)
                            .addGroup(BgOperacionesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        BgOperacionesLayout.setVerticalGroup(
            BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgOperacionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel)
                    .addComponent(DireccionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoLabel)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BgOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoLabel)
                    .addComponent(TipoSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BgInventario.add(BgOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 620, 260));

        NotaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NotaLabel.setText("Nota: Seleccione un cliente para realizar las operaciones");
        BgInventario.add(NotaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 510, -1));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        BgInventario.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BgInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void TelefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoTxtActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home vista = new Home();
        vista.setVisible(true);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Clientes vista = new Clientes();
        ClienteControlador controlador = new ClienteControlador(vista);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgInventario;
    private javax.swing.JPanel BgOperaciones;
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel DireccionLabel;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel NotaLabel;
    private javax.swing.JScrollPane Panel;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JLabel TelefonoLabel;
    private javax.swing.JTextField TelefonoTxt;
    private javax.swing.JLabel TipoLabel;
    private javax.swing.JComboBox<String> TipoSeleccion;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables

    public JPanel getBgInventario() {
        return BgInventario;
    }

    public JButton getBtnActualizar() {
        return BtnActualizar;
    }

    public JButton getBtnAgregar() {
        return BtnAgregar;
    }

    public JButton getBtnBorrar() {
        return BtnBorrar;
    }

    public JButton getBtnLimpiar() {
        return BtnLimpiar;
    }

    public JLabel getDireccionLabel() {
        return DireccionLabel;
    }

    public JTextField getDireccionTxt() {
        return DireccionTxt;
    }

    public JLabel getEmailLabel() {
        return EmailLabel;
    }

    public JTextField getEmailTxt() {
        return EmailTxt;
    }

    public JPanel getBgOperaciones() {
        return BgOperaciones;
    }

    public JButton getBtnRegresar() {
        return BtnRegresar;
    }

    public JLabel getNotaLabel() {
        return NotaLabel;
    }

    public JLabel getTituloLabel() {
        return TituloLabel;
    }

    public JLabel getNombreLabel() {
        return NombreLabel;
    }

    public JTextField getNombreTxt() {
        return NombreTxt;
    }

    public JScrollPane getPanel() {
        return Panel;
    }

    public JTable getTablaDatos() {
        return TablaDatos;
    }

    public JLabel getTelefonoLabel() {
        return TelefonoLabel;
    }

    public JTextField getTelefonoTxt() {
        return TelefonoTxt;
    }

    public JLabel getTipoLabel() {
        return TipoLabel;
    }

    public JComboBox<String> getTipoSeleccion() {
        return TipoSeleccion;
    }

    public JLabel TituloLabel() {
        return TituloLabel;
    }

    //Accesores
}
